default: &default
  adapter: postgresql
  encoding: unicode
  pool:     <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 5 %>
  host:     <%= ENV['PG_HOST'] || 'localhost' %>
  port:     <%= ENV['PG_PORT'] || 5432 %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  database: <%= ENV['DATABASE_NAME'] %>

development:
  <<: *default
  database: petbooking_auth_development

test:
  <<: *default
  database: petbooking_auth_test

production:
  <<: *default
